project:
  type: book
  output-dir: docs

book:
  title: "ThamesWater Andrio Emilio application"
  author: "Andrio Emilio"
  favicon: "logo.png"
  navbar:
    logo: "logo.png"
    collapse: true
    collapse-below: lg
    background: light
    reader-mode: true
    search: true
    right:
      - icon: github
  sidebar:
    title: "AE application"
    style: docked
    reader-mode: true
  repo-url: https://github.com/andrioemilio/Interview_prep
  repo-actions: [issue]
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - prep.qmd
    - ExcelStudy.qmd
    - SQLStudy.qmd
    - PowerBIStudy.qmd
    - PythonAnalysis.qmd

bibliography: references.bib

format:
  html:
    title-block-banner: images/banner.jpg
    #cover-image: img/casa.png
  #css: textures.css
    theme: 
    # textures.css
        light: [cerulean, flatly]
        dark: [cerulean, darkly]
    code-link: true
    number-sections: false
  pdf:
    # documentclass: scrreprt
    documentclass: scrbook

editor: visual

